feat(config, linting): Дополнена документация, добавлен линтер, рефакторинг докерфайлов под slim версию
Добавлен раздел в документацию, отвечающий за объяснения работы с линтером. Добавлен и сам линтер с конфигурационными файлами. Произведён рефакторинг всех Dockerfile's под slim версию. Изменены источники в документации

Changelog: feat

diff --git a/Dockerfile.certified b/Dockerfile.certified
--- a/Dockerfile.certified
+++ b/Dockerfile.certified
@@ -1,91 +1,22 @@
 ## Definite image args
 ARG image_registry
 ARG image_name=astra
-ARG image_version=1.8.1
+ARG image_version=1.8.2-slim
 
 # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
-#                         Base image                          #
-#               First stage, prepare environment              #
+#                         Build image                         #
+#              First stage, build static component            #
 # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
-FROM ${image_registry}${image_name}:${image_version} AS base-stage
+FROM ${image_registry}${image_name}:${image_version} AS build-stage
 
 SHELL ["/bin/bash", "-exo", "pipefail", "-c"]
-
-## Def initial arg(will be replaced with docker build opt)
-ARG version=1.0.0
 
 ## ENV for build args
 ENV \
-    VERSION="${version}" \
-    LANG=C.UTF-8 \
-    LC_ALL=C.UTF-8 \
     TERM=linux \
     TZ=Etc/UTC \
-## https://devcenter.heroku.com/articles/tuning-glibc-memory-behavior
-    MALLOC_ARENA_MAX=2
-
-## Copy build scripts
-COPY scripts/. /usr/local/sbin/
-
-## Update locales
-## Always use the latest version available for the current DEB distribution
-# hadolint ignore=DL3008, DL3027
-RUN \
-    apt update \
-    && apt-env.sh apt -y install --no-install-recommends --no-install-suggests -qq \
-## Configure locales
-        locales \
-## Update locales
-    && printf 'ru_RU.UTF-8 UTF-8\nen_US.UTF-8 UTF-8' >> /etc/locale.gen \
-    && locale-gen \
-    && dpkg-reconfigure locales \
-    # LANG=ru_RU.UTF-8
-    && update-locale \
-## Check locale
-    && locale -a | grep 'en_US.utf8' \
-    && locale -a | grep 'ru_RU.utf8' \
-## Remove cache
-    && apt-clean.sh \
-## Def version container
-    && echo "Minimal Container version ${VERSION}" > /etc/issue
-
 ## Set locale language
-ENV LANG=en_US.utf8
-
-## Reduce perl-base: hardlink->symlink
-RUN \
-    PERL_BASE=/usr/bin \
-    && find "${PERL_BASE}/" -wholename "${PERL_BASE}/perl5*" -exec ln -fsv perl {} ';' \
-    && ls -li "${PERL_BASE}/perl"*
-
-## Prevent services from auto-starting, part 1
-RUN \
-    SERVICE_POLICY_SBIN='/usr/sbin/policy-rc.d' \
-    && SERVICE_POLICY_BIN='/usr/bin/policy-rc.d' \
-    && rm -f "${SERVICE_POLICY_SBIN}" "${SERVICE_POLICY_BIN}" \
-    && echo '#!/bin/sh' > "${SERVICE_POLICY_BIN}" \
-    && echo 'exit 101' >> "${SERVICE_POLICY_BIN}" \
-    && chmod 0755 "${SERVICE_POLICY_BIN}" \
-    && ln -s "${SERVICE_POLICY_BIN}" "${SERVICE_POLICY_SBIN}"
-
-## Divert function with link true
-RUN \
-    divert_true() { rm-divert.sh "${1}" ; ln -sv /bin/true "${1}" ; } \
-## Prevent services from auto-starting, part 2
-    && divert_true /sbin/start-stop-daemon \
-## Always report that we're in chroot
-    && divert_true /usr/bin/ischroot \
-## Hide systemd helpers
-    && divert_true /usr/bin/deb-systemd-helper \
-    && divert_true /usr/bin/deb-systemd-invoke
-
-# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
-#                         Second image                        #
-#              Second stage, build static component           #
-# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
-FROM base-stage AS build-stage
-
-SHELL ["/bin/bash", "-exo", "pipefail", "-c"]
+    LANG=en_US.UTF8
 
 ## Temporary directory for installer
 WORKDIR /opt
@@ -96,8 +27,8 @@ COPY configuration/su-exec.c su-exec.c
 ## Compile su-exec
 # hadolint ignore=DL3008, DL3027
 RUN \
-    apt update \
-    && apt-env.sh apt -y install --no-install-recommends --no-install-suggests -qq \
+    --mount=type=bind,source=./scripts,target=/usr/local/sbin,readonly \
+    apt-install.sh \
 ## Compile .c
         gcc \
         libc-dev \
@@ -106,40 +37,34 @@ RUN \
     && rm su-exec.c \
 ## Remove packages
     && apt-env.sh apt-remove.sh gcc libc-dev \
-    && apt-clean.sh \
-    && find /usr/local/sbin/ ! -type d -ls -delete
+    && apt-clean.sh
 
 # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
-#                        Final image                          #
-#             Third stage, install final components           #
+#                     Environment image                       #
+#   Second stage, install components and prepare environment  #
 # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
-FROM base-stage AS final-stage
+FROM ${image_registry}${image_name}:${image_version} AS environment-stage
 
 SHELL ["/bin/bash", "-exo", "pipefail", "-c"]
 
-## Set base label
-LABEL \
-    maintainer="Vladislav Avdeev" \
-    organization="NGRSoftlab"
-
 ## Def initial arg(will be replaced with docker build opt)
+ARG version=1.0.0
 ARG postgrespro_package_suffix='std-15'
-ARG postgrespro_version=15
 
-## Set postgres variables
+## ENV for build args
 ENV \
-    PG_USER=postgres \
+    TERM=linux \
+    TZ=Etc/UTC \
+## Set locale language
+    LANG=en_US.UTF8 \
+## Set postgres variables
     PG_DIR="/var/lib/pgpro/${postgrespro_package_suffix}" \
-    PG_VERSION_SUFFIX="${postgrespro_package_suffix}" \
-    PG_MAJOR="${postgrespro_version}"
+    PG_VERSION_SUFFIX="${postgrespro_package_suffix}"
 
 ## https://github.com/hadolint/hadolint/wiki/DL3044
 ENV \
     PGDATA="${PG_DIR}/data" \
-    BINDIR="/opt/pgpro/${PG_VERSION_SUFFIX}/bin" \
-    PG_OOM_ADJUST_VALUE=0 \
-    PG_OOM_ADJUST_FILE=/proc/self/oom_score_adj \
-    PG_LOG="${PG_DIR}/pgstartup-data.log"
+    BINDIR="/opt/pgpro/${PG_VERSION_SUFFIX}/bin"
 ENV PATH="${BINDIR}:${PATH}"
 
 ## Copy entrypoint file
@@ -148,13 +73,18 @@ COPY --chmod=0755 configuration/docker-entrypoint.sh /usr/local/bin/
 ## Copy from build stage
 COPY --from=build-stage --chmod=0700 /usr/local/bin/su-exec /usr/local/bin/
 
+## Copy issue
+COPY docs/issue /etc/issue
+
 ## Temporary directory for installer
 WORKDIR /tmp
 
 ## Install postgres
 ## First step mounting local repo for install certified postgres
 # hadolint ignore=DL3008, DL3027
-RUN --mount=type=bind,source=./opt,target=/tmp/distribution,readonly \
+RUN \
+    --mount=type=bind,source=./opt,target=/tmp/distribution,readonly \
+    --mount=type=bind,source=./scripts,target=/usr/local/sbin,readonly \
 ## Create tmp repo
     install -g root -o _apt -m 0755 -d /tmp/apt-repo \
     && cp -a /tmp/distribution/* /tmp/apt-repo \
@@ -165,12 +95,13 @@ RUN --mount=type=bind,source=./opt,target=/tmp/distribution,readonly \
     && groupadd -r postgres --gid=999 \
 ## https://salsa.debian.org/postgresql/postgresql-common/blob/997d842ee744687d99a2b2d95c1083a2615c79e8/debian/postgresql-common.postinst#L32-35
     && useradd -r -g postgres --uid=999 --home-dir="${PG_DIR}" --shell=/bin/bash postgres \
-    && apt update \
-    && apt-env.sh apt -y install --no-install-recommends --no-install-suggests -qq \
+    && apt-install.sh \
 ## For import key into system
         gpg \
 ## Init agent
         dumb-init \
+## Establish free,ps and etc
+        procps \
 ## Postgres ep import
         libnss-wrapper \
         xz-utils \
@@ -185,20 +116,22 @@ RUN --mount=type=bind,source=./opt,target=/tmp/distribution,readonly \
 ## Added gpg key in keyring store
     && gpg --dearmor -o /usr/share/keyrings/postgres-pro.pgp \
         < /tmp/apt-repo/keys/GPG-KEY-POSTGRESPRO \
-## Fetch repo
-    && apt update \
-## Install postgres
-    && apt-env.sh apt -y install --no-install-recommends --no-install-suggests -qq \
+## Fetch repo and install postgres
+    && apt-install.sh \
         postgrespro-"${PG_VERSION_SUFFIX}"-server \
         ## additional facilities for Postgres Pro
         postgrespro-"${PG_VERSION_SUFFIX}"-contrib \
+## Set postgres build environment
+    && postgres-set-environment.sh "${PG_VERSION_SUFFIX}" \
+## Test postgres
+    && postgres --version \
 ## Prune temporary information about repository
     && rm -rf /tmp/apt-repo \
         /usr/share/keyrings/postgres-pro.pgp \
         /etc/apt/sources.list.d/postgrespro.list \
-## Test postgres
-    && postgres --version \
+## Create ep dirs
     && mkdir /docker-entrypoint-initdb.d \
+## Overriding the default configuration location
     && mkdir -p /usr/share/postgresql \
     && dpkg-divert --add --rename --divert \
         "/usr/share/postgresql/postgresql.conf.sample.dpkg" \
@@ -215,159 +148,84 @@ RUN --mount=type=bind,source=./opt,target=/tmp/distribution,readonly \
 ## This 1777 will be replaced by 0700 at runtime (allows semi-arbitrary "--user" values)
     && install --verbose --directory --owner postgres --group postgres --mode 1777 "${PGDATA}" \
     && install --verbose --directory --owner postgres --group postgres --mode 1777 "/etc/postgresql" \
-## Remove cache
-    && apt-clean.sh \
-## Test su-exec
-    && su-exec nobody true
-
-## Set volume creates a mount point with the specified name and marks it as holding externally mounted volumes from native host or other containers
-VOLUME "${PGDATA}"
-
 ## Remove unwanted binaries
-RUN \
-    rm-binary.sh \
+    && rm-binary.sh \
         addgroup \
-        addpart \
         adduser \
-        apt-ftparchive \
-        agetty \
-        badblocks \
-        blkdiscard \
-        blkid \
-        blkzone \
-        blockdev \
-        bsd-write \
-        chage \
-        chcpu \
-        chfn \
-        chgpasswd \
-        chmem \
-        chpasswd \
-        chsh \
-        cpgr \
-        cppw \
-        crontab \
-        ctrlaltdel \
-        debugfs \
         delgroup \
-        delpart \
         deluser \
-        dmesg \
-        dumpe2fs \
-        e2freefrag \
-        e2fsck \
-        e2image \
-        e2label \
-        e2mmpstatus \
-        e2scrub \
-        'e2scrub*' \
-        e2undo \
-        e4crypt \
-        e4defrag \
-        expiry \
-        faillock \
-        fdformat \
-        fincore \
-        findfs \
-        fsck \
-        'fsck.*' \
-        fsfreeze \
-        fstrim \
-        getty \
-        gpasswd \
-        groupadd \
-        groupdel \
-        groupmems \
-        groupmod \
-        grpck \
-        grpconv \
-        grpunconv \
-        hwclock \
-        isosize \
-        last \
-        lastb \
-        ldattach \
-        losetup \
-        lsblk \
-        lsirq \
-        lslogins \
-        mcookie \
-        mesg \
-        mke2fs \
-        mkfs \
-        'mkfs.*' \
-        mkhomedir_helper \
-        mklost+found \
-        mkswap \
-        mount \
-        newgrp \
-        newusers \
-        pam-auth-update \
-        pam_getenv \
-        pam_namespace_helper \
-        pam_timestamp_check \
-        partx \
         passwd \
-        pivot_root \
-        pwck \
-        pwconv \
-        pwhistory_helper \
-        pwunconv \
-        raw \
-        readprofile \
-        resize2fs \
-        resizepart \
-        rtcwake \
-        sg \
-        shadowconfig \
         su \
         sulogin \
-        swaplabel \
-        swapoff \
-        swapon \
-        switch_root \
-        tune2fs \
-        umount \
-        unix_chkpwd \
-        unix_update \
         update-passwd \
         useradd \
         userdel \
         usermod \
-        utmpdump \
-        vigr \
-        vipw \
-        wall \
-        wdctl \
-        wipefs \
-        write \
-        'write.*' \
-        zramctl \
-    && rm -f \
-        /bin/lastb \
-        /bin/sg \
-        /sbin/getty
-
-## Cleanup deduplicate
-# hadolint ignore=DL3027, DL4006
-RUN \
-    apt update \
-    && apt-env.sh apt -y install --no-install-recommends --no-install-suggests -qq \
-        jdupes \
-## Prune deduplicate
-    && echo; du -xd1 /usr/ | sort -Vk2; echo \
-    && jdupes -1LSpr /usr/ \
-    && echo; du -xd1 /usr/ | sort -Vk2; echo \
-## Remove packages
-    && apt-env.sh apt-remove.sh jdupes \
+## Remove cache
     && apt-clean.sh
 
 ## Prune unused files
 RUN \
-    find /usr/local/sbin/ ! -type d -ls -delete \
-    && find /tmp/ ! -type d -ls -delete \
-    && find /run/ -mindepth 1 -ls -delete || : \
-    && install -d -m 01777 /run/lock
+    --mount=type=bind,source=./scripts,target=/usr/local/sbin,readonly \
+    find /run/ -mindepth 1 -ls -delete || : \
+    && install -d -m 01777 /run/lock \
+## Deduplication cleanup
+    && dedup-clean.sh /usr/ \
+## Def version container
+    && echo "Build PostgresPro container version ${version}" >> /etc/issue \
+## Test su-exec
+    && su-exec nobody true \
+## Check can be preview /etc/issue
+    && { \
+        grep -qF 'cat /etc/issue' /etc/bash.bashrc \
+        || echo 'cat /etc/issue' >> /etc/bash.bashrc; \
+    }
+
+# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
+#                        Final image                          #
+#             Third stage, compact optimize layer             #
+# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
+FROM scratch
+
+COPY --from=environment-stage / /
+
+## Set base label
+LABEL \
+    maintainer="Vladislav Avdeev" \
+    organization="NGRSoftlab"
+
+## Def initial arg(will be replaced with docker build opt)
+ARG postgrespro_package_suffix='std-15'
+ARG postgrespro_version=15
+ARG version=1.0.0
+
+## ENV for build args
+ENV \
+    VERSION="${version}" \
+    TERM=linux \
+    TZ=Etc/UTC \
+    TERM='xterm-256color' \
+    DEBIAN_FRONTEND='noninteractive' \
+## Set locale language
+    LANG=en_US.UTF8 \
+## Set postgres variables
+    PG_USER=postgres \
+    PG_DIR="/var/lib/pgpro/${postgrespro_package_suffix}" \
+    PG_VERSION_SUFFIX="${postgrespro_package_suffix}" \
+    PG_MAJOR="${postgrespro_version}"
+
+## https://github.com/hadolint/hadolint/wiki/DL3044
+ENV \
+    PGDATA="${PG_DIR}/data" \
+    BINDIR="/opt/pgpro/${PG_VERSION_SUFFIX}/bin" \
+    PG_OOM_ADJUST_VALUE=0 \
+    PG_OOM_ADJUST_FILE=/proc/self/oom_score_adj \
+    PG_LOG="${PG_DIR}/pgstartup-data.log"
+ENV PATH="${BINDIR}:/usr/local/go/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
+
+## Set volume creates a mount point with the specified name and marks it as holding
+## externally mounted volumes from native host or other containers
+VOLUME "${PGDATA}"
 
 ## Be gentle and expose port
 EXPOSE 5432/tcp
